export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"642610338d8a1a002089e7df",
				"642610338d8a1a002089e7e2"
			]
		},
		"642610338d8a1a002089e7df": {
			"id": "642610338d8a1a002089e7df",
			"name": "404",
			"pageUrl": "404"
		},
		"642610338d8a1a002089e7e2": {
			"id": "642610338d8a1a002089e7e2",
			"name": "index",
			"pageUrl": "index"
		}
	},
	"mode": "production",
	"projectType": "create-react-app",
	"site": {
		"styles": {},
		"seo": {
			"sitemapFileType": "autogenerated",
			"customSitemapXml": "matnez",
			"robotsFileType": "autogenerated"
		}
	}
}